name: release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create zip (js + bat)
        id: package
        shell: pwsh
        run: |
          $Version='${{ github.ref_name }}'
          $zip="poi_messageflow_bridge_$Version.zip"
          Compress-Archive -Path @('poi_messageflow_bridge.js','start_poi.bat') -DestinationPath $zip -Force
          "zip_name=$zip" >> $env:GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: ${{ steps.package.outputs.zip_name }}
